### ISSUE TITLE
MFA support

### ISSUE THREAD

**Issue by dpasman** [lswiderski/yet-another-garmin-connect-client#9]
Hi,

Thanks for your work!

I used this client and it worked very well. However, with the new ECG update I enabled MFA to my account. My old Home Assistant automation creating the POST command stopped working now. I tried adding the mfacode key in the body, but it does not seem to be supported (yet). Or is there just no documentation? Since your Android app is working with MFA. 

My idea was to create an automation running the POST command like before to trigger an email with the MFA code, then entering the MFA code in an input_text helper which triggers a new automation running the same POST command with the MFAcode in the body. Is this possible at the moment?

Example POST command from HomeAssistant:
```
action: rest_command.send_bodymetrics_to_yagcc
data_template:
  weight: "{{ states('sensor.weight') }}"
  email: myemail
  password: secretpass
  percentFat: "{{ states('sensor.body_fat') }}"
  percentHydration: "{{ states('sensor.water') }}"
  boneMass: "{{ states('sensor.bone_mass') }}"
  muscleMass: "{{ states('sensor.muscle_mass') }}"
  visceralFatRating: "{{ states('sensor.visceral_fat') }}"
  metabolicAge: "{{ states('sensor.metabolic_age') }}"
  bodyMassIndex: "{{ states('sensor.bmi') }}"
  mfaCode: "{{ states('input_text.garmin_mfa_code_input') }}" 
```

Thank you in advance.
